version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dermin_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dermin_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - dermin_network

  backend:
    build: .
    container_name: dermin_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017/dermin_db?authSource=admin
      DATABASE_NAME: dermin_db
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - dermin_network

volumes:
  mongodb_data:

networks:
  dermin_network:
    driver: bridge
